project="project_id_from_google_iam"
machine_type="n1-standard-1"
region="us-central1"
credential_file_path="credentials/dev-cred.json"
zone= "us-central1-c"
app_name="dev-app"
github_repo_name="cloud-run-cicd-demo"
environment="dev"	